# Permalinks
permalink:           pretty

# Setup
title:               DaulPav.id
tagline:             Software-defined Radio, Communication Systems, Wireless
url:                 https://daulpav.id
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports
sass:
  sass_dir:          _sass
  style:            :compressed

# Specify where the static images for figures are stored
default:
  - scope:
      path: "static/images"
    values:
      image: true

# Personal information
author:
  name:              Paul David
  url:               https://github.com/daulpavid
  email:             daulpavid@daulpav.id
  linkedin:          DaulPavid
  github_username:   DaulPavid
  twitter:           daulpavid

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/daulpavid/daulpavid.github.io

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
